version: '3.9'

services:
  # MongoDB Service
  mongodb:
    image: mongo:6.0
    container_name: blog_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - blog_network

  # Backend Service (Node.js/Express)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blog_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - blog_network
    restart: unless-stopped

  # Frontend Service (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: blog_frontend
    environment:
      - REACT_APP_API_URL=http://backend:8000
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - blog_network
    restart: unless-stopped

  # Nginx Reverse Proxy (Optional)
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: blog_nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - blog_network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  blog_network:
    driver: bridge
